
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>        
<!-- Custom PPMX additional info -->
<?php if($block->getIsMethodActive()) : ?>
    <!-- Add Custom PayPal Message for pending payments -->
    <?php if ($block->isPaymentPending() && !empty($block->getPendingMessage())) : ?>
        <div id="warning" class="message notice">
            <div><?php echo $block->escapeHtml($block->getPendingMessage()) ?></div>
        </div>
    <?php endif; ?>
    <!-- Add PayPal Logo -->
    <img src="<?php echo $block->escapeHtml($block->getPayPalLogo()) ?>" border="0" />
<?php endif; ?>
<!-- End of Custom PPPlus additional info --> 
    
    